# Generated by Django 3.1.7 on 2021-02-25 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='videos/content/')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnails/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='video_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
