# Generated by Django 3.1.7 on 2021-03-04 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_auto_20210304_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='video_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
