# Generated by Django 3.1.7 on 2021-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210304_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
