# Generated by Django 3.1.7 on 2021-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_creatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='profile_picture',
            field=models.ImageField(default='youtube_clone\\static\\pictures\\download.jpg', upload_to='images/profile_pics'),
        ),
    ]
