# Generated by Django 3.1.7 on 2021-03-16 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_auto_20210315_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile_pic.jpg', upload_to='images/profile_pics'),
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Subscribe', 'Subscribe'), ('Unubscribe', 'Unubscribe')], default='Subscribe', max_length=15)),
                ('channel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.video')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.creatorprofile')),
                ('subscriber', models.ManyToManyField(blank=True, default=None, related_name='channel_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
