# Generated by Django 3.1.7 on 2021-03-16 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210316_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='channel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.channel'),
        ),
    ]
