# Generated by Django 3.1.7 on 2021-03-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20210316_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='channel_owner',
            new_name='channel',
        ),
    ]
