# Generated by Django 3.1.7 on 2021-03-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210316_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
